# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clothingStore', '0003_auto_20170930_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productLine',
            new_name='orderLine',
        ),
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
